defaults:
  - _self_
hydra:
  run:
    dir: ${log_dir}
#_target_: "src.agent.train.TrainVLAAgent"

 # Misc
log_dir: /n/fs/robot-data/data/oxe_gripper_label
name: ${seed}
device: cuda
inspect_data: True
seed: 79

# Logs and Evals
batch_size: 32
max_batches: 2000

# Actions
final_action_clip_value: 1.0  # data normalized in [-1,1]
cond_steps: 1
horizon_steps: 1
action_dim: 7 # EEF_POS

data:
  val:  # stil aplying image randomization
    split:  # full val split
    shuffle_buffer_size: 0 #10000
    buffer_size: 8192
  train:
    dataset_mix: oxe_27
    split: train
    data_path: /n/fs/vla-mi/datasets/OXE/
    # data_path: /n/fs/robot-data/vlm-syn/oxe_data
    window_size: 1
    action_horizon: ${horizon_steps}
    skip_unlabeled: False
    load_proprio: True
    shuffle_buffer_size: 0 #200000
    num_parallel_calls: 60
    traj_transform_threads: 30
    traj_read_threads: 30
    image_aug: False


